version: 2

models:
  - name: int_order_items_enhanced
    description: "Order items enriched with product and order context for detailed analysis"
    columns:
      - name: order_item_id
        description: "Unique identifier for each order item"
        tests:
          - unique
          - not_null
      - name: order_id
        description: "Foreign key to orders table"
        tests:
          - not_null
      - name: product_id
        description: "Foreign key to products table"
        tests:
          - not_null
      - name: revenue_dollars
        description: "Revenue attributed to this order item (0 if order not completed)"
        tests:
          - not_null
      - name: discount_percentage
        description: "Percentage discount applied to this item"
      - name: is_discounted
        description: "Flag indicating if item was sold at a discount"
        tests:
          - not_null
      - name: category_clean
        description: "Standardized product category"
        tests:
          - accepted_values:
              values: ['Electronics', 'Footwear', 'Kitchen', 'Fitness', 'Home Office', 'Other']

  - name: int_customer_order_history
    description: "Customer-level aggregated order history and behavioral metrics"
    columns:
      - name: customer_id
        description: "Unique identifier for each customer"
        tests:
          - unique
          - not_null
      - name: total_orders
        description: "Total number of orders placed by customer"
        tests:
          - not_null
      - name: completed_orders
        description: "Number of successfully completed orders"
        tests:
          - not_null
      - name: total_revenue_dollars
        description: "Total revenue generated by customer"
        tests:
          - not_null
      - name: customer_segment
        description: "Customer segmentation based on order frequency"
        tests:
          - accepted_values:
              values: ['One-time', 'Occasional', 'Frequent', 'Unknown']
      - name: customer_status
        description: "Customer activity status based on recency"
        tests:
          - accepted_values:
              values: ['Active', 'Dormant', 'Inactive']
