[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "dbt-core>=1.10.4",
    "dbt-duckdb>=1.9.4",
    "dbt-postgres>=1.9.0",
]
