version: 2

models:
  - name: stg_customers
    description: "Cleaned and standardized customer data from raw sources"
    columns:
      - name: customer_id
        description: "Unique identifier for each customer"
        tests:
          - unique
          - not_null
      - name: email
        description: "Customer email address (normalized to lowercase)"
        tests:
          - not_null
          - unique
      - name: first_name
        description: "Customer first name"
        tests:
          - not_null
      - name: last_name
        description: "Customer last name"
        tests:
          - not_null
      - name: full_name
        description: "Concatenated first and last name"
      - name: email_provider
        description: "Email provider category (Gmail, Yahoo, etc.)"
        tests:
          - accepted_values:
              values: ['Gmail', 'Yahoo', 'Hotmail', 'Outlook', 'Other']
      - name: is_valid_customer
        description: "Flag indicating if customer record passes basic validation"
        tests:
          - not_null

  - name: stg_orders
    description: "Cleaned and standardized order data from raw sources"
    columns:
      - name: order_id
        description: "Unique identifier for each order"
        tests:
          - unique
          - not_null
      - name: customer_id
        description: "Foreign key reference to customer"
        tests:
          - not_null
          - relationships:
              to: ref('stg_customers')
              field: customer_id
      - name: order_date
        description: "Date when the order was placed"
        tests:
          - not_null
      - name: status
        description: "Current status of the order"
      - name: order_status_clean
        description: "Standardized order status"
        tests:
          - accepted_values:
              values: ['completed', 'pending', 'cancelled', 'refunded', 'unknown']
      - name: total_amount_cents
        description: "Total order amount in cents"
        tests:
          - not_null
      - name: total_amount_dollars
        description: "Total order amount in dollars"
      - name: is_completed_order
        description: "Flag indicating if order is completed"
        tests:
          - not_null

  - name: stg_products
    # Intentionally leaving this model undocumented to show mixed coverage
    
  - name: stg_order_items
    # Intentionally leaving this model undocumented to show mixed coverage
